### ISSUE TITLE
ME Region

### ISSUE THREAD

**Issue by base64bits** [sadponyguerillaboy/Swift-Apple-EFI-Patcher#2]
Thanks so much for creating this tool, this is now allowing me to write new EFI firmwares much faster than using Windows.

Sorry to ask this here, but how do I identify what ME region goes with a specific Mac? I don't see anything that matches either by board number etc.

Thanks again!

**Comment by sadponyguerillaboy** [comment]
The ME regions are categorized by Board ID. You can check a board ID with:
`ioreg -l | grep -i board-id
       |   "board-id" = <"Mac-F22589C8">`

**Comment by base64bits** [comment]
Thanks a lot for your reply, In some cases some boards cannot be booted to be able to see this info inside de Mac, but with the serial number you can check what your model identifier on sites like everymac.com for example a model identifier on a MacBook Air Early 2014 the model identifier will be MacBook6,1 and in the Me_Regions directory you will find a folder named MBA61 that will be the correct ME_Region, inside there there are a few options, I am assuming that one needs to select the same OS as what the Mac has installed.

I also see that not all ME_Regions are listed, for example I have a MacBook Pro Early 2011 and the model identifier is MacBook8,3 the closest one I could find was MBP81, will that one work?

Some of the notes I made here are very basic, but I made them in case someone like me comes here and finds it helpful.

**Comment by sadponyguerillaboy** [comment]
The ME Regions have been extracted from Apple OS Updates, which used the same categorization method of Model Identifier. In each directory, there might be multiple ME Region versions. Each of those files will have a corresponding OS version in the name to indicate what OS they were extracted from. In many cases, the ME Regions between OS releases are identical. You can use a program like Hex Fiend to open both files and then compare them. If they are all identical, then it doesn't matter which one you use. But if there are differences, then use the one from the same OS version installed on the system.

As for the MacbookPro8,3 (Macbook Pro 2011 17" A1297), it's the same as the 8,1 (15").
