### ISSUE TITLE
problems with  CH341A

### ISSUE THREAD

**Issue by jafjas78** [sadponyguerillaboy/Swift-Apple-EFI-Patcher#3]
i have a question. btw love the software finally i can do it on a mac. but tried to instal CH341A but i get
"Couldn't open device 1a86:5512. Error: Programmer initialization failed"
a bad programmer ? i don't know what i do wrong

(i normal use EZP2010 USB SPI EEPROM Programmer)

**Comment by sadponyguerillaboy** [comment]
if you use your programmer with just flashrom (not with the swift efi patcher) via the terminal, do you experience the same issues? If so, it's a configuration / connection issue you will need to sort out. From what I can recall, if your spi chip is not correctly attached this will happen.

**Comment by jafjas78** [comment]
Thanks for the reply.
After some tryouts I figured out that the programmer couldn’t read the flashrom map right. After I fixed that and solder the bios the right position. It worked like a charm 👊🏼🔥

Thnx so much

**Comment by sadponyguerillaboy** [comment]
Great, glad it got sorted!
